import Head from 'next/head'
import dynamic from 'next/dynamic'

var Editor = dynamic(() => import("../../components/Editor/Editor"), {
  ssr: false
})

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <Editor  />
      </main>
    </div>
  )
}